django_app/post/urls.py
from django.conf.urls import url

from .views import post_view

app_name = 'post'
urlpatterns = [
    url(r'^$', post_view.post_list, name='post_list'),
    url(r'^create/$', post_view.post_create, name='post_create'),
    url(r'^order/(?P<post_pk>\d+)/$', post_view.order, name='order'),
]

django_app/post/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ImageField(upload_to='post', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

django_app/post/views/post_view.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect

from ..form import PostForm, PaymentsForm
from ..models import Post

User = get_user_model()


__all__ =(
    'post_list',
    'post_create',
    'order',
)

def post_list(request):
    posts = Post.objects.all()

    context = {
        'posts': posts
    }
    return render(request, 'post/post_list.html', context)


def post_create(request):
    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            photo = form.cleaned_data['photo']
            Post.objects.create(
                author=request.user,
                photo=photo,
            )
        return redirect('post:post_list')
    elif request.method == 'GET':
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


def order(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'GET':
        form = PostForm()
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'post/order.html', context=context)

django_app/templates/post/order.html
{% extends 'base/base.html' %}

{% block content %}
    {% include 'include/post.html' %}
    {% csrf_token %}
    <div class="payments">
        <a href="{% url 'charge' %}">
            <button type="submit" class="btn btn-primary btn-lg btn-block">결제하기</button>
        </a>
    </div>
{% endblock %}

django_app/templates/post/post_create.html
{% extends 'base/base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form }}
    <button class="btn btn-default">만들기</button>
    </form>
{% endblock %}

django_app/templates/post/post_list.html
{% extends 'base/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="row">
            <div class="col-xs-2  col-sm-2 col-md-2"></div>
            <div class="col-xs-8  col-sm-8 col-md-8">
                {% include 'include/post.html' %}
                <div class="row">
                    <a href="{% url 'post:order' post_pk=post.pk %}">
                        <button class="btn btn-default">위 상품 주문페이지로</button>
                    </a>
                </div>
            </div>

            <div class="col-xs-2  col-sm-2 col-md-2"></div>
        </div>
    {% endfor %}

{% endblock %}