django_app/member/urls.py
from django.conf.urls import url

from . import views

app_name = 'member'
urlpatterns = [
    url(r'^create/$', views.create_user, name='create_user'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

django_app/post/urls.py
from django.conf.urls import url

from .views import post_view

app_name = 'post'
urlpatterns = [
    url(r'^$', post_view.post_list, name='post_list'),
    url(r'^create/$', post_view.post_create, name='post_create'),
    url(r'^order/(?P<post_pk>\d+)/$', post_view.order, name='order'),
]

django_app/templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Binstagram</title>
</head>
<body>
<nav class="top-nav">
    <div class="container">
        <div class="row">
            <div class="col-xs-1  col-sm-1 col-md-1">로고</div>
            <div class="col-xs-2  col-sm-2 col-md-2"><a href="{% url 'post:post_list' %}"><h2>빈스타그램</h2></a></div>
            <div class="col-xs-6  col-sm-6 col-md-6">
                <input type="text" placeholder="검색">
            </div>
            <div class="col-xs-3  col-sm-3 col-md-3">
                <a href="#">
                    <img src="{% static 'images/icon_explore.png' %}" alt="">
                </a>
                <a href="#">
                    <img src="{% static 'images/icon_heart.png' %}" alt="">
                </a>
                <a href="#">
                    <img src="{% static 'images/icon_profile.png' %}" alt="">
                </a>
            </div>
        </div>
    </div>
</nav>
<div class="menu">
    <div class="row">
        <a href="{% url 'post:post_create' %}">
            <button class="btn btn-default">포스팅 만들기</button>
        </a>
        {% if user.is_authenticated %}
            현재 {{ user.username }}로 접속중
            <a href="{% url 'member:logout' %}">
                <button class="btn btn-danger">로그아웃</button>
            </a>
        {% else %}
            <a href="{% url 'member:login' %}">
                <a href="{% url 'member:login' %}">
                    <button class="btn btn-default">로그인 하기</button>
                </a>
            </a>
        {% endif %}
        <a href="">
            <button class="btn btn-success">페이스북 로그인</button>
        </a>
        <a href="{% url 'member:create_user' %}">
            <button class="btn btn-success">회원가입</button>
        </a>
    </div>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>